% NOTE: This script trains with original resolution by cropping
%% instead of resizing when reading batches 

% function hybrid_trires_limit30_hardmine_res101(mode)
function hr_res101(mode)

if nargin < 1 || isempty(mode)
  mode = 'train';
end

overWrite = false;
gpus = [2]; 
modelType = 'resnet-101-simple';
pretrainModelPath = 'matconvnet/imagenet-resnet-101-dag.mat';
inputSize = [500, 500];
trainFn = '@cnn_train_dag_hardmine';
batchGetterFn = '@cnn_get_batch_hardmine';
maxClusterSize = [inf, inf];
minClusterSize = [10, 10];

nmsThresh = 0.3;
vis = false;
if vis
  probThresh = 0.5;
else
  probThresh = 0.03;
end

batchSize = 14;
numSubBatches = 1;

% tag = 'scaled-trires-limit30-hardmine';
tag = '';

testSet = 'val';
testTag = '';
testSize = nan;

clusterNoResize = true;
clusterNum = 25;
clusterName = 'scaled';
skipLRMult = [0 1 0.1];
learningRates = [1e-4*ones(1,30)];

switch mode
  case 'train'
    % we still need an input size so that we know what to crop 
    cnn_widerface('multiRes', false, 'extraInputPad', true, ...
                  'inputSize', inputSize, ...
                  'clusterName', clusterName, ...
                  'clusterNoResize', clusterNoResize, ...
                  'learningRate', learningRates, ...
                  'maxClusterSize', maxClusterSize, ...
                  'minClusterSize', minClusterSize, ...
                  'tag', tag, ...
                  'trainFn', trainFn, ...
                  'batchGetterFn', batchGetterFn, ...
                  'numEpochs', 50, ...
                  'batchSize', batchSize, ...
                  'numSubBatches', numSubBatches,...
                  'fcnScale', 'fcn8s', 'clusterNum', clusterNum, ...
                  'lossType', 'logistic', ...
                  'sampleSize', 256, 'posFraction', 0.5, ...
                  'modelType', modelType, ...
                  'gpus', gpus, ...
                  'pretrainModelPath', pretrainModelPath, ...
                  'skipLRMult', skipLRMult);
  case 'test'
    for i = 47
      cnn_widerface_test_with_zoom('overWrite', overWrite, ...
                                   'multiRes', false, ...
                                   'clusterName', clusterName, ...
                                   'testMultires', true, ...
                                   'noUpsampling', false, ...
                                   'noOrgres', false, ...
                                   'noDownsampling', false, ...
                                   'clusterNum', clusterNum, ...
                                   'clusterNoResize', clusterNoResize,...
                                   'tag', tag, ...
                                   'testTag', testTag, ...
                                   'extraInputPad', true, ...
                                   'inputSize', inputSize, ...
                                   'batchSize', batchSize, 'numSubBatches', numSubBatches,...
                                   'fcnScale', 'fcn8s', ...
                                   'lossType', 'logistic', 'learningRate', 1e-4, ...
                                   'sampleSize', 256, 'posFraction', 0.5, ...
                                   'modelType', modelType, ...
                                   'pretrainModelPath', 'matconvnet/imagenet-resnet-50-dag.mat',...
                                   'skipLRMult', skipLRMult, ...
                                   'vis', vis, 'gpus', gpus, ...
                                   'probThresh', probThresh, ...
                                   'nmsThresh', nmsThresh, ...
                                   'testSize', testSize, ...
                                   'testSet', testSet, ...
                                   'testEpoch', i);
    end
  case 'eval'
    for i = 47
      cnn_widerface_eval_new('multiRes', false, ...
                             'testMultires', true, ...
                             'testSize', testSize, ...
                             'noUpsampling', false, ...
                             'noOrgres', false, ...
                             'noDownsampling', false, ...
                             'clusterNum', clusterNum, ...
                             'clusterName', clusterName, ...
                             'clusterNoResize', clusterNoResize, ...
                             'tag', tag, ...
                             'extraInputPad', true, ...
                             'inputSize', inputSize, ...
                             'minOverlap', [0.5], ...
                             'batchSize', batchSize, 'numSubBatches', numSubBatches,...
                             'fcnScale', 'fcn8s', ...
                             'lossType', 'logistic', 'learningRate', 1e-4, ...
                             'sampleSize', 256, 'posFraction', 0.5, ...
                             'modelType', modelType, ...
                             'pretrainModelPath', 'matconvnet/imagenet-resnet-50-dag.mat',...
                             'skipLRMult', skipLRMult, ...
                             'vis', vis, 'gpus', [1], ...
                             'draw', false, ...
                             'testEpoch', i, ...
                             'probThresh', probThresh,...
                             'nmsThresh', nmsThresh);
    end
  case 'range'
    for ci = 1:25
      for i = 36:50
        cnn_widerface_eval_range('multiRes', false, ...
                                 'clusterSet', [ci], ...
                                 'testMultires', true, ...
                                 'testSize', testSize, ...
                                 'noUpsampling', false, ...
                                 'noOrgres', false, ...
                                 'noDownsampling', false, ...
                                 'clusterNum', clusterNum, ...
                                 'clusterName', clusterName, ...
                                 'clusterNoResize', clusterNoResize, ...
                                 'tag', tag, ...
                                 'testTag', testTag, ...
                                 'maxClusterSize', maxClusterSize, ...
                                 'minClusterSize', minClusterSize, ...
                                 'extraInputPad', true, ...
                                 'inputSize', inputSize, ...
                                 'minOverlap', [0.5], ...
                                 'batchSize', batchSize, 'numSubBatches', numSubBatches,...
                                 'fcnScale', 'fcn8s', ...
                                 'lossType', 'logistic', 'learningRate', 1e-4, ...
                                 'sampleSize', 256, 'posFraction', 0.5, ...
                                 'modelType', modelType, ...
                                 'pretrainModelPath', 'matconvnet/imagenet-resnet-50-dag.mat',...
                                 'skipLRMult', skipLRMult, ...
                                 'vis', vis, 'gpus', gpus, ...
                                 'draw', false, ...
                                 'testEpoch', i, ...
                                 'probThresh', probThresh);
      end
    end
end
